name: "Dependabot Automerge - Action"

on:
  pull_request_target:
    types:
      - opened

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              body: '@dependabot merge'
            })
          github-token: ${{github.token}}
